### ISSUE TITLE
Publishing releases to github!

### ISSUE THREAD

**Issue by happysalada** [leona/helix-gpt#1]
Hi, first of all, thank you for making this!
This is really nice!

Would you mind publishing an initial release to github ?
The reason I ask is that I would like to have a go at packaging this with nix.
This will likely take time, but having a first release (no matter the number) would be a first step.

ps: just in case you are interested, if you know about the litellm project https://github.com/zya/litellmjs , that could be an easy way to support other models.

**Comment by happysalada** [comment]
Alright I'm going to have a question though.
I've submitted early efforts at https://github.com/NixOS/nixpkgs/pull/283643
I've tried running the build:bin and just copying that over but that doesn't seem to work.
Maybe no need to build at all and just use makebinarywrapper with bun ?
since you know the package best, let me know what you think.

**Comment by leona** [comment]
> Alright I'm going to have a question though. I've submitted early efforts at [NixOS/nixpkgs#283643](https://github.com/NixOS/nixpkgs/pull/283643) I've tried running the build:bin and just copying that over but that doesn't seem to work. Maybe no need to build at all and just use makebinarywrapper with bun ? since you know the package best, let me know what you think.

I haven't packaged anything for Nix before so I can't help much sorry. What happened when you used the precompiled one though?

**Comment by happysalada** [comment]
no worries at all, let's just talk about how to run this.
When I tried running the binary built by build:bin, it just gave me the bun help message, saying this was missing an argument.
rather than running build:bin, could I not `bun ./app.ts` and be done with it ?
(the other way would be to just fetch precompiled binaries, I'll do that if all else fails).

**Comment by happysalada** [comment]
alright I have an initial version running with
`bun run --prefer-offline --no-install ./src/app.ts`

one small but potential improvement is to just throw an error if the required environment variables are not found.

**Comment by leona** [comment]
> no worries at all, let's just talk about how to run this. When I tried running the binary built by build:bin, it just gave me the bun help message, saying this was missing an argument. rather than running build:bin, could I not `bun ./app.ts` and be done with it ? (the other way would be to just fetch precompiled binaries, I'll do that if all else fails).

I tried with autoPatchelf earlier and had the same problem. Strange.

> alright I have an initial version running with `bun run --prefer-offline --no-install ./src/app.ts`
> 
> one small but potential improvement is to just throw an error if the required environment variables are not found.

Nice one. It should do that already, see here https://github.com/leona/helix-gpt/blob/b1a7bbe4f260086646a7306124c742d52d3c9660/src/config.ts#L67 A single API key is the only required config

**Comment by happysalada** [comment]
Nice!
I'm going to wait a couple more days before updating my pull request to nixpkgs, just to make sure I don't contribute a too stale version.
I think this issue can be closed now, thank you again!
