### ISSUE TITLE
[Request] Expose workspace command to temporarily disable suggestions (and code actions)

### ISSUE THREAD

**Issue by jpaju** [leona/helix-gpt#10]
First of all, thanks for the amazing work! Not having Copilot in Helix was really an issue for me, but not anymore 🙏 

Sometimes I'd like to temporarily disable the copilot/GPT suggestions, when it is making too many or irrelevant suggestions. Currently I'm not aware that there are any other way of accomplishing this than modifying the `languages.toml` file. I think it would be nice if the LSP would expose a [workspace command](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#command), which could be executed from Helix using the `:lsp-workspace-command`.

What do you think?

**Comment by leona** [comment]
Hey thanks for the suggestion. I think that's reasonable, I'll take a look at implementing it today.

**Comment by leona** [comment]
Ok unfortunately it might not make sense to add this right now. Commands don't show up for me in that list, and I found out why https://github.com/helix-editor/helix/issues/9017 I'll add this to the todo list for when it's possible

**Comment by jpaju** [comment]
Alright, thanks for looking into this!
