### ISSUE TITLE
[BUG] SyntaxError: Import named 'parseArgs' not found in module 'util'.

### ISSUE THREAD

**Issue by sommerper** [leona/helix-gpt#11]
What I did:
```
git clone git@github.com:leona/helix-gpt.git
cd helix-gpt
bun install
bun build:bin
ln -s /home/xxx/development/github/helix-gpt/dist/helix-gpt /home/xxx/.local/bin/helix-gpt
chmod +x /home/xxx/.local/bin/helix-gpt
helix-gpt --authCopilot
```
I'm getting:
```SyntaxError: Import named 'parseArgs' not found in module 'util'.```

Am I missing a few steps here?

**Comment by leona** [comment]
> What I did:
> 
> ```
> git clone git@github.com:leona/helix-gpt.git
> cd helix-gpt
> bun install
> bun build:bin
> ln -s /home/xxx/development/github/helix-gpt/dist/helix-gpt /home/xxx/.local/bin/helix-gpt
> chmod +x /home/xxx/.local/bin/helix-gpt
> helix-gpt --authCopilot
> ```
> 
> I'm getting: `SyntaxError: Import named 'parseArgs' not found in module 'util'.`
> 
> Am I missing a few steps here?

What version of Bun are you running?

**Comment by sommerper** [comment]
```
❯ bun --version
1.0.6
```

That one is on me ;-)
So I did a 
```
bun upgrade
bun install
bun build:bin
```

and then I'm getting
```
❯ helix-gpt --authCopilot
69 |     });
70 |   }
71 |   async request(request) {
72 |     const { endpoint, method, body, headers, params, url, timeout } = request;
73 |     let requestUrl = new URL(endpoint, url || this.url);
74 |     log("fetch", endpoint);
         ^
TypeError: log is not a function. (In 'log("fetch", endpoint)', 'log' is undefined)
      at /$bunfs/root/helix-gpt:74:5
      at request (/$bunfs/root/helix-gpt:71:19)
      at /$bunfs/root/helix-gpt:208:24
      at deviceCode (/$bunfs/root/helix-gpt:207:22)
      at /$bunfs/root/helix-gpt:347:28
      at copilot_auth_default (/$bunfs/root/helix-gpt:345:35)
      at /$bunfs/root/helix-gpt:417:9
```

**Comment by leona** [comment]
> ```
> ❯ bun --version
> 1.0.6
> ```
> 
> That one is on me ;-) So I did a
> 
> ```
> bun upgrade
> bun install
> bun build:bin
> ```
> 
> and then I'm getting
> 
> ```
> ❯ helix-gpt --authCopilot
> 69 |     });
> 70 |   }
> 71 |   async request(request) {
> 72 |     const { endpoint, method, body, headers, params, url, timeout } = request;
> 73 |     let requestUrl = new URL(endpoint, url || this.url);
> 74 |     log("fetch", endpoint);
>          ^
> TypeError: log is not a function. (In 'log("fetch", endpoint)', 'log' is undefined)
>       at /$bunfs/root/helix-gpt:74:5
>       at request (/$bunfs/root/helix-gpt:71:19)
>       at /$bunfs/root/helix-gpt:208:24
>       at deviceCode (/$bunfs/root/helix-gpt:207:22)
>       at /$bunfs/root/helix-gpt:347:28
>       at copilot_auth_default (/$bunfs/root/helix-gpt:345:35)
>       at /$bunfs/root/helix-gpt:417:9
> ```

Ah that's a really annoying Bun issue that they haven't fixed yet. I've pushed a change to remove the log statements from that file, should resolve it if you pull the latest.

**Comment by sommerper** [comment]
Thanks a bunch!
Now I don't get any errors anymore.
I still can't see it Helix but I think that may be something with my config.
I'll close this issue and look into the config issues I might have.
