### ISSUE TITLE
Add a shebang to the bundled file?

### ISSUE THREAD

**Issue by MatthiasGrandl** [leona/helix-gpt#15]
I did expect I could just execute the downloaded javascript file with bun installed on my system, but since there is no shebang, the system doesn't know how to execute it. I would suggest adding the following shebang to the top of the file:

```
#!/usr/bin/env bun
```

**Comment by leona** [comment]
Cheers for the suggestion. I'll add that in a build step.

**Comment by leona** [comment]
Added in 0.26
