### ISSUE TITLE
Support for codeium

### ISSUE THREAD

**Issue by happysalada** [leona/helix-gpt#17]
**Is your feature request related to a problem? Please describe.**
Codeium is an alternative code specific completion engine that is free for individuals and *supposedly* better than copilot
https://codeium.com/

**Describe the solution you'd like**
Having an alternative handler codeium would be amazing

**Describe alternatives you've considered**
Not supporting it

**Additional context**
    
Let me know if you need more precisions.

Thanks a lot for making this !

**Comment by leona** [comment]
Cheers for the suggestion. Having a free option would be great, so I've started work on this. Should be merged in the next few days.

**Comment by leona** [comment]
@happysalada supported in 0.27
