### ISSUE TITLE
llama.cpp endpoint alternative

### ISSUE THREAD

**Issue by Arian-D** [leona/helix-gpt#3]
First of all, thank you for your work on this!

There is a server implementation for [llama.cpp](https://github.com/ggerganov/llama.cpp) and [llamafile](https://github.com/Mozilla-Ocho/llamafile), and I use them very frequently. [The API](https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md#api-endpoints) happens to be compatible with the OpenAI API.

It would be very helpful to set the URI with environment variable flag for people who self-host llama.cpp or llamafile.

P.S. I noticed the [base URI is hardcoded](https://github.com/leona/helix-gpt/blob/c54099630b3c3fcaed767f0e13f7c9fe99c958d5/src/openai.ts#L31). I'm not very knowledgeable in TS, but if I find the time I might make a PR.

**Comment by leona** [comment]
Hey cheers for the suggestion. I've pushed a change to allow that with the `OPENAI_ENDPOINT` env var, so as long as it's fully compatible it should work.

I tried llama.cpp a while back and didn't get great results, but let me know how you get on.

**Comment by Arian-D** [comment]
Thank you for the quick change!

I learned that the llama.cpp server implementation is not fully compatible with OpenAI's API, but [llama-cpp-python's API](https://llama-cpp-python.readthedocs.io/en/latest/server/) is.

As you noted, it wasn't great (especially on my old thinkpad), and the requests timed out, but they were valid. I'll try it again on a beefier machine and will report back. Until then I'll suffer with [gptel](https://github.com/karthink/gptel) on Emacs :joy:.
