### ISSUE TITLE
InvalidExe ? 

### ISSUE THREAD

**Issue by peteringram0** [leona/helix-gpt#5]
Im getting the following error log:

```
2024-01-26T21:45:37.138 helix_lsp::transport [ERROR] gpt err <- "error: Failed to run \"helix-gpt.js\" due to error InvalidExe\n"
```

`helix-gpt` is in my path. Im on a M1.

```
[language-server.gpt]
command = "bun"
args = ["run", "helix-gpt.js"]
```

**Comment by lemontheme** [comment]
I don't know much about Bun, but I'd be surprised if it checks your path. Try providing the complete path to the JS file?

**Comment by peteringram0** [comment]
> I don't know much about Bun, but I'd be surprised if it checks your path. Try providing the complete path to the JS file?

It runs directly in a terminal. Well it executes and i get an error "z is not a function" from the helix-gpt.js lib

**Comment by leona** [comment]
> > I don't know much about Bun, but I'd be surprised if it checks your path. Try providing the complete path to the JS file?
> 
> It runs directly in a terminal. Well it executes and i get an error "z is not a function" from the helix-gpt.js lib

Could you try clone the repo and build it manually with `bun run build:smol`?

**Comment by peteringram0** [comment]
yeah this resolves my issue but now im getting issue reported in #7.
