### ISSUE TITLE
[BUG] triggering github's abuse systems

### ISSUE THREAD

**Issue by lun-4** [leona/helix-gpt#63]
**helix-editor version**
24.3

**helix-gpt version**
0.31

**Describe the bug**
turns out github just emailed me!

> Hello @lun-4,

> On behalf of the GitHub Security team, I want to first extend our gratitude for your continued use of GitHub and for being a valued member of the GitHub community.

> Recent activity on your account caught the attention of our abuse-detection systems. This activity included use of Copilot that was indicative of scripted interactions or of an otherwise deliberately unusual or strenuous nature. While we have not yet restricted Copilot access for your account, further anomalous activity could result in a temporary suspension of your Copilot access.

> While I’m unable to share specifics on rate limits, we prohibit all use of our servers for any form of excessive automated bulk activity, as well as any activity that places undue burden on our servers through automated means. Please refer to our Acceptable Use Policies on this topic: https://docs.github.com/site-policy/acceptable-use-policies/github-acceptable-use-policies#4-spam-and-inauthentic-activity-on-github.

> Please also refer to our Terms for Additional Products and Features for GitHub Copilot for specific terms: https://docs.github.com/site-policy/github-terms/github-terms-for-additional-products-and-features#github-copilot.

> Sincerely,
> GitHub Security

---

I do not use other editors than helix, in turn, there is no extension other than `helix-gpt` that could be triggering github's abuse systems for copilot. I am not automating helix in any way, but it's possible they ran some detection on the headers that helix-gpt uses to look like vscode. it doesn't look like the copilot vscode extension is under any kind of permissive license that would allow for reverse engineering, so I don't think an official GH ticket would give any results (it might even backfire and take the repo down, but that's the worst case), I am open to ideas though.

my current opinion is if GH is going to play cat-and-mouse, then we should act accordingly as the mouse. we should move towards continuously updating fingerprints such that we look more and more like vscode, that is a major maintenance request that I do not think I would be able to take on, myself. but it is a way. (of course, not even talking about possibly having to move the repo somewhere else, killing the social factor of having this plugin known, entirely. maybe a migration to codeberg could work, which is another **major maintenance request**, and is one I would put a lot of thought before actually going on with a random's requests).

**Comment by oschwald** [comment]
I received a similar message. They actually suspended my Copilot access because of it. I also only used Copilot with this `helix-gpt`. I ended up just canceling my Copilot subscription as the GitHub support was threatening the termination of my GitHub account if the "abuse" continued.

**Comment by leona** [comment]
I've been receiving the same, and tried to reply but never got a response. @oschwald did you try reaching out to support?

**Comment by oschwald** [comment]
Yes, I reached out to support, but it was not very enlightening. They refused to provide any more details about the "abuse" (or even confirm if it was coming from my IP). They just kept repeating that if it continues they will terminate my Copilot access and my GitHub account.

**Comment by leona** [comment]
> Yes, I reached out to support, but it was not very enlightening. They refused to provide any more details about the "abuse" (or even confirm if it was coming from my IP). They just kept repeating that if it continues they will terminate my Copilot access and my GitHub account.

I've just merged a PR from someone that only allows one active request. Maybe this will help.

**Comment by lun-4** [comment]
we should probably verify the headers sent in https://github.com/leona/helix-gpt/blob/2aba4d5809089ca68692f353affc37542110b351/src/providers/github.ts#L124 to update the vscode version, and get a way to store machine id and session id to be reused, so microsoft's internal systems don't think we have thousands of computers

**Comment by defasdefbe** [comment]
The other OSS editors (like XCode/Sublime Text/etc) handled this by making sure to send their actual name in the headers instead of sending 

https://github.com/leona/helix-gpt/blob/2aba4d5809089ca68692f353affc37542110b351/src/providers/github.ts#L126-L129

**Comment by benoxoft** [comment]
I also got an email from copilot yesterday. I hope this issue will be resolved. I like helix and being able to use copilot with it is great.
