### ISSUE TITLE
[BUG] Command failed with status 400 bad request

### ISSUE THREAD

**Issue by petar-n-mce-ext** [leona/helix-gpt#70]
**helix-editor version**
helix 24.3

**helix-gpt version**
0.34

OS: Windows 11
build from source to binary with bun all required env variabels added to the system
HANDLER=copilot

**Describe the bug**
executing code action result in following message
![image](https://github.com/user-attachments/assets/f58d3eef-8728-496f-b6ca-df87ca4a1a62)

**helix-gpt logs**
Helix GPT output logs. Pass `--logFile /app/helix-gpt.log` to save them.

**note**   not sure how to get that on windows ☝️ 

**helix logs**
[helix.log](https://github.com/user-attachments/files/16823715/helix.log)

**Comment by ElYaiko** [comment]
I get 400 too when `ctrl+x` with Codeium

`Fetch failed with status 400 body {"code":"invalid_argument","message":"validation error:\n - document.editor_language: value length must be at least 1 characters [string.min_len]: validation error:\n - document.editor_language: value length must be at least 1 characters [string.min_len]","details":[{"type":"cockroach.errorspb.EncodedError","value":"Ep4p...","debug":{"wrapper":{"cause":{"wrapper":{"cause":{"wrapper":{"cause":{"wrapper":{"cause":{"wrapper":{"cause":{"leaf":{"message":"validation error:\n - document.editor_language: value length must be at least 1 characters [string.min_len]","details":{"originalTypeName":"github.com/bufbuild/protovalidate-go/internal/errors/*errors.ValidationError","errorTypeMark":{"familyName":"github.com/bufbuild/protovalidate-go/internal/errors/*errors.ValidationError"}}}},"message":"validation error:\n - document.editor_language: value length must be at least 1 characters [string.min_len]: validation error:\n - document.editor_language: value length must be at least 1 characters [string.min_len]","details":{"originalTypeName":"github.com/cockroachdb/errors/errutil/*errutil.withPrefix","errorTypeMark":{"familyName":"github.com/cockroachdb/errors/errutil/*errutil.withPrefix"},"reportablePayload":["validation error:\n - document.editor_language: value length must be at least 1 characters [string.min_len]"],"fullDetails":{"@type":"type.googleapis.com/cockroach.errorspb.StringPayload","msg":"validation error:\n - document.editor_language: value length must be at least 1 characters [string.min_len]"}}}},"details":{"originalTypeName":"github.com/cockroachdb/errors/withstack/*withstack.withStack","errorTypeMark":{"familyName":"github.com/cockroachdb/errors/withstack/*withstack.withStack"},"reportablePayload":["\ngithub.com/Exafunction/Exafunction/exa/connect_utils.(*validateInterceptor).WrapUnary.func1\n\texa/connect_utils/validate.go:36\ngithub.com/Exafunction/Exafunction/exa/language_server.initServers.NewRemoteModeInterceptor.func9.1\n\texa/connect_utils/remote_mode.go:28\ngithub.com/Exafunction/Exafunction/exa/connect_utils.(*LogErrorsServerInterceptor).WrapUnary.func1\n\texa/connect_utils/interceptor.go:53\ngithub.com/easyCZ/connect-go-prometheus.(*Interceptor).WrapUnary.func1\n\texternal/com_github_easycz_connect_go_prometheus/interceptor.go:73\ngithub.com/Exafunction/Exafunction/exa/connect_utils.(*SentryErrorInterceptor).WrapUnary.func1\n\texa/connect_utils/interceptor.go:214\nconnectrpc.com/connect.NewUnaryHandler[...].func2\n\texternal/com_connectrpc_connect/handler.go:70\nconnectrpc.com/connect.(*Handler).ServeHTTP\n\texternal/com_connectrpc_connect/handler.go:238\ngithub.com/Exafunction/Exafunction/exa/language_server_pb;language_server_.NewLanguageServerServiceHandler.func1\n\tbazel-out/k8-opt/bin/exa/language_server_pb/language_server_connect_go_proto_/github.com/Exafunction/Exafunction/exa/language_server_pb;language_server_/language_server.connect.go:1410\nnet/http.HandlerFunc.ServeHTTP\n\tGOROOT/src/net/http/server.go:2171\nnet/http.(*ServeMux).ServeHTTP\n\tGOROOT/src/net/http/server.go:2688\ngithub.com/Exafunction/Exafunction/exa/language_server.initServers.(*Cors).Handler.func10\n\texternal/com_github_rs_cors/cors.go:231\nnet/http.HandlerFunc.ServeHTTP\n\tGOROOT/src/net/http/server.go:2171\ngithub.com/Exafunction/Exafunction/exa/language_server.initServers.(*Handler).Handle.(*Handler).handle.func11\n\texternal/com_github_getsentry_sentry_go/http/sentryhttp.go:124\nnet/http.HandlerFunc.ServeHTTP\n\tGOROOT/src/net/http/server.go:2171\ngolang.org/x/net/http2.(*serverConn).runHandler\n\texternal/org_golang_x_net/http2/server.go:2369\nruntime.goexit\n\tsrc/runtime/asm_amd64.s:1695"]}}},"details":{"originalTypeName":"github.com/Exafunction/Exafunction/exa/go_utils/*go_utils.withConnectCode","errorTypeMark":{"familyName":"github.com/Exafunction/Exafunction/exa/go_utils/*go_utils.withConnectCode"},"reportablePayload":["invalid_argument"]}}},"details":{"originalTypeName":"github.com/cockroachdb/errors/withstack/*withstack.withStack","errorTypeMark":{"familyName":"github.com/cockroachdb/errors/withstack/*withstack.withStack"},"reportablePayload":["\ngithub.com/Exafunction/Exafunction/exa/connect_utils.(*validateInterceptor).WrapUnary.func1\n\texa/connect_utils/validate.go:37\ngithub.com/Exafunction/Exafunction/exa/language_server.initServers.NewRemoteModeInterceptor.func9.1\n\texa/connect_utils/remote_mode.go:28\ngithub.com/Exafunction/Exafunction/exa/connect_utils.(*LogErrorsServerInterceptor).WrapUnary.func1\n\texa/connect_utils/interceptor.go:53\ngithub.com/easyCZ/connect-go-prometheus.(*Interceptor).WrapUnary.func1\n\texternal/com_github_easycz_connect_go_prometheus/interceptor.go:73\ngithub.com/Exafunction/Exafunction/exa/connect_utils.(*SentryErrorInterceptor).WrapUnary.func1\n\texa/connect_utils/interceptor.go:214\nconnectrpc.com/connect.NewUnaryHandler[...].func2\n\texternal/com_connectrpc_connect/handler.go:70\nconnectrpc.com/connect.(*Handler).ServeHTTP\n\texternal/com_connectrpc_connect/handler.go:238\ngithub.com/Exafunction/Exafunction/exa/language_server_pb;language_server_.NewLanguageServerServiceHandler.func1\n\tbazel-out/k8-opt/bin/exa/language_server_pb/language_server_connect_go_proto_/github.com/Exafunction/Exafunction/exa/language_server_pb;language_server_/language_server.connect.go:1410\nnet/http.HandlerFunc.ServeHTTP\n\tGOROOT/src/net/http/server.go:2171\nnet/http.(*ServeMux).ServeHTTP\n\tGOROOT/src/net/http/server.go:2688\ngithub.com/Exafunction/Exafunction/exa/language_server.initServers.(*Cors).Handler.func10\n\texternal/com_github_rs_cors/cors.go:231\nnet/http.HandlerFunc.ServeHTTP\n\tGOROOT/src/net/http/server.go:2171\ngithub.com/Exafunction/Exafunction/exa/language_server.initServers.(*Handler).Handle.(*Handler).handle.func11\n\texternal/com_github_getsentry_sentry_go/http/sentryhttp.go:124\nnet/http.HandlerFunc.ServeHTTP\n\tGOROOT/src/net/http/server.go:2171\ngolang.org/x/net/http2.(*serverConn).runHandler\n\texternal/org_golang_x_net/http2/server.go:2369\nruntime.goexit\n\tsrc/runtime/asm_amd64.s:1695"]}}},"details":{"originalTypeName":"github.com/Exafunction/Exafunction/exa/go_utils/*go_utils.withSha","errorTypeMark":{"familyName":"github.com/Exafunction/Exafunction/exa/go_utils/*go_utils.withSha"},"reportablePayload":["8fde..."]}}}}]} url: /exa.language_server_pb.LanguageServerService/GetCompletions`

**Comment by petar-n-mce-ext** [comment]
Closing as not able to reproduce anymore now works as expected
