### ISSUE TITLE
[Request] Trigger completion also on `Ctrl-x`

### ISSUE THREAD

**Issue by lemontheme** [leona/helix-gpt#8]
This message occurs frequently in the helix-gpt log file:

```
skipping |  | not in | {,(,),=,>, ,,,:,.,<,/
```

I'm assuming its related to what you describe in your [comment on the Helix thread about how helix-gpt works](https://github.com/helix-editor/helix/discussions/4037#discussioncomment-8259874).

Obviously, it makes total sense not to be sending completion requests every key press. It would be useful, however, to be able to trigger a request manually with the [builtin Ctrl-x keybinding for autocompletion](https://docs.helix-editor.com/keymap.html#:~:text=commit_undo_checkpoint-,Ctrl%2Dx,completion,-Ctrl%2Dr) (which I spam all the time).

Without it, use cases like the following (i.e. code generation based on a description) remain out of reach.

```python
# function that takes a number x and multiplies it by 2
.. def double(x [...]
```

Also, I imagine that the set of characters/keywords that signal sensible contexts for auto-fetching completions varies depending on programming languages. 

Of course, all this depends on whether LSP servers are able to differentiate between automatic requests and manually triggered requests. Any ideas?

**Comment by leona** [comment]
Hey thanks for the suggestion. I've removed the check for the trigger character, which allows you to use `ctrl + x` now. Will be available in the next release.

**Comment by leona** [comment]
Added in [0.10](https://github.com/leona/helix-gpt/releases/tag/0.10)

**Comment by lemontheme** [comment]
Awesome, thanks! :) I can confirm it works (minus other problems currently being debugged).
